[phases.setup]
nixPkgs = ["python311", "ffmpeg", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run upload_video_mixer.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --browser.gatherUsageStats=false --server.enableCORS=true --server.enableXsrfProtection=false"

[variables]
PYTHONUNBUFFERED = "1"
IS_RAILWAY = "true"
