[build]
builder = "dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[deploy.healthcheck]]
path = "/"
method = "GET"
timeout = 30
interval = 60

[variables]
PORT = "8501"
PYTHONUNBUFFERED = "1"
IS_RAILWAY = "true"
